### ISSUE TITLE
🗳️ Add hotbox workstation for seeds

### ISSUE THREAD

**Issue by jonathan-robertson** [jonathan-robertson/gmo-farming#9]
This would be where you can let seeds sit, undisturbed in zombie meat for the necessary period of time.

## Tasks
- [x] Add Workstation Block
- [x] Add audio for open/close
- [x] Prevent Hold E while place allowing to choose materials
- [x] Add Journal Tip?
- [x] Add Localization/Names
- [x] Add Unlock Trigger for Recipe
- [x] Add Recipe
- [x] Add Seed category?
- [x] Adjust sort order so it makes sense

## Workstation Block
![image](https://user-images.githubusercontent.com/5396045/164998442-c9f3cd5d-d9c9-40a3-93ad-82610bb1df5e.png)

## Category Image
![image](https://user-images.githubusercontent.com/5396045/164998451-28973a53-6cc6-4b31-a938-7d5695a3f8aa.png)
